### PR TITLE
Add support for beta.workflowy.com

### PR DESCRIPTION
**Pull request by MattHulse**

### CODE REVIEW

**Comment by MattHulse** [comment]
Links to Issue #7

**Comment by MattHulse** [comment]
It turns out beta.workflowy.com is no longer a thing.  Experimental features are turned on in settings and the url to workflowy no longer changes.  

Closing this PR.

**Comment by MattHulse** [comment]
It turns out beta.workflowy.com is still being used as a staging area so it is the first place to get new features.  I think this change will still be beneficial.

**Comment by Wojnach** [comment]
Thanks for the PR! :D

**Pull request merged**
